# Generated by Django 4.2.1 on 2023-05-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brewery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
